# tachytome
g script-binding tachytome/goto
d script-binding tachytome/trash

# Rotate video
Ctrl+r cycle_values video-rotate 90 180 270 0

# Copy path
Ctrl+c show-text "Copied: ${path}"; run sh -c 'echo -n "${path}" | wl-copy'

# Toggle OSC
DEL script-binding modernz/visibility

# Reload subtitles
r sub-reload

# Moving
Alt+LEFT seek -1
Alt+RIGHT seek 1
LEFT seek -5
RIGHT seek 5
Ctrl+LEFT seek -10
Ctrl+RIGHT seek 10
Ctrl+Shift+LEFT seek -60
Ctrl+Shift+RIGHT seek 60

# Arrow volume controls
UP add volume 10
DOWN add volume -10
Shift+UP add volume 5
Shift+DOWN add volume -5

# Zoom
Alt+i add video-zoom 0.01
Alt+o add video-zoom -0.01
Alt+0 set video-zoom 0; set video-pan-x 0; set video-pan-y 0
