# Keep open and don't autoplay
keep-open=always

# Automatically open all the files in the same dir
autocreate-playlist=same

# Volume
volume=50
volume-max=150

# OSD
osc=no
osd-bar=no
osd-on-seek=no
title-bar=no
watch-later-options-remove=sub-pos

# Misc
hr-seek=yes
cache=yes
demuxer-max-bytes=2GiB
demuxer-max-back-bytes=1GiB
target-colorspace-hint=yes

# GPU Acceleration
profile=high-quality
hwdec=nvdec,auto-safe

# Scaling
dscale=mitchell
cscale=spline36
scale-antiring=0.7
cscale-antiring=0.7

# Deband
# Toggle it by pressing b
deband-iterations=4
deband-threshold=48
deband-range=16
deband-grain=5

# Interpolation
# This only kicks in when the video FPS and display Hz don't match
# For example, watching a 24FPS video on a 60Hz display
video-sync=display-resample
interpolation=yes
tscale=oversample

# Autocrop
script-opts-append=autocrop-auto=no

[performance]
profile=fast
interpolation=no
video-sync=audio
scale-antiring=0
cscale=bilinear
cscale-antiring=0

[svp]
input-ipc-server=/tmp/mpvsocket
hr-seek-framedrop=no
watch-later-options-remove=vf
interpolation=no
video-sync=audio
